#!/bin/sh

# 修改基本设置
uci set system.@system[0].hostname='OpenWrt-GXNAS'
uci set system.@system[0].zonename='Asia/Shanghai'
uci set system.@system[0].timezone='CST-8'
uci -q delete system.ntp.server
uci add_list system.ntp.server='ntp.aliyun.com'
uci add_list system.ntp.server='time1.cloud.tencent.com'
uci add_list system.ntp.server='time.apple.com'
uci add_list system.ntp.server='time.windows.com'
uci commit system

# LuCI 默认语言
uci -q set "luci.main.lang=zh_cn"
uci -q commit "luci"

# 修复 Netdata 启动脚本权限问题
[ -f /etc/init.d/netdata ] && chmod +x /etc/init.d/netdata

# iStore 默认语言
uci -q set "istore.istore.istore_vue_lang=zh_cn"
uci -q commit "istore"

# TurboACC 插件默认启用 BBR 拥塞控制
if [ -f "/etc/config/turboacc" ]; then
    uci -q set "turboacc.config.tcpcca=bbr"
    uci -q commit "turboacc"
    /etc/init.d/turboacc restart >/dev/null 2>&1
fi

# 预先下载OpenClash Meta内核及依赖文件
CLASH_META_URL=$(curl -sL https://api.github.com/repos/MetaCubeX/Clash.Meta/releases/tags/Prerelease-Alpha | grep -o '"browser_download_url": *"[^"]*mihomo-linux-amd64-compatible-alpha-[^"]*\.gz"' | awk -F '"' '{print $4}' | head -n 1)
wget -qO- $CLASH_META_URL | gunzip -c > files/etc/openclash/core/clash_meta
chmod +x files/etc/openclash/core/clash*
GEOIP_URL=https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat
GEOSITE_URL=https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
COUNTRY_FULL_URL=https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb
wget -qO- $GEOIP_URL > files/etc/openclash/GeoIP.dat
wget -qO- $GEOSITE_URL > files/etc/openclash/GeoSite.dat
wget -qO- $COUNTRY_FULL_URL > files/etc/openclash/Country.mmdb

exit 0
