#!/bin/sh

# 修复 default-settings 问题
uci set system.@system[0].hostname='OpenWrt-GXNAS'
uci set system.@system[0].zonename='Asia/Shanghai'
uci set system.@system[0].timezone='CST-8'
uci -q delete system.ntp.server
uci add_list system.ntp.server='ntp.aliyun.com'
uci add_list system.ntp.server='time1.cloud.tencent.com'
uci add_list system.ntp.server='time.apple.com'
uci add_list system.ntp.server='time.windows.com'
uci commit system

# LuCI 默认语言
uci -q set "luci.main.lang=zh_cn"
uci -q commit "luci"

# 修复 netdata 配置脚本缺失
uci -q delete luci.netdata
uci set luci.netdata="netdata"
uci set luci.netdata.name="NetData"
uci set luci.netdata.url="/netdata/"
uci commit luci
rm -f /usr/lib/lua/luci/controller/netdata.lua
rm -f /usr/lib/lua/luci/controller/admin/netdata.lua
cat > /usr/lib/lua/luci/controller/admin/netdata.lua << 'EOF'
module("luci.controller.admin.netdata", package.seeall)
function index()
    entry({"admin", "services", "netdata"}, template("netdata"), _("NetData"), 60)
end
EOF

# iStore 默认语言
uci -q set "istore.istore.istore_vue_lang=zh-cn"
uci -q commit "istore"

# TurboACC 插件默认启用 BBR 拥塞控制（内核 6.18 自带最新 BBR）
if [ -f "/etc/config/turboacc" ]; then
	uci -q set "turboacc.config.tcpcca"="bbr"
	uci -q commit "turboacc"
	/etc/init.d/turboacc restart >/dev/null 2>&1
fi

exit 0
